server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-route
              uri: http://localhost:8090
              predicates:
                - Path=/auth/**
            - id: rh-route
              uri: http://localhost:8083
              predicates:
                - Path=/rh/**
            - id: employee-route
              uri: http://localhost:8087
              predicates:
                - Path=/employes/**
            - id: absence-route
              uri: http://localhost:8084
              predicates:
                - Path=/absences/**
            - id: conge-route
              uri: http://localhost:8088
              predicates:
                - Path=/conges/**
            - id: emploi-route
              uri: http://localhost:8085
              predicates:
                - Path=/emplois/**

jwt:
  secret: "mySecretKeyMySecretKeyMySecretKeyMySecretKey"
